# Generated by Django 6.0.6 on 2026-06-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('dative', models.CharField(max_length=50, verbose_name='название (дательный падеж)')),
                ('accusative', models.CharField(max_length=50, verbose_name='название (винительный падеж)')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7, unique=True, verbose_name='номер')),
                ('profile', models.CharField(max_length=255, verbose_name='профиль')),
                ('course_code', models.CharField(max_length=10, verbose_name='направление (код курса)')),
                ('stage', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура')], max_length=20, verbose_name='ступень обучения')),
                ('year_of_admission', models.PositiveSmallIntegerField(verbose_name='год зачисления')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='номер')),
            ],
            options={
                'verbose_name': 'семестр',
                'verbose_name_plural': 'семестры',
                'ordering': ['number'],
            },
        ),
    ]
