# Generated by Django 6.0.6 on 2026-06-24 22:35

import django.db.models.deletion
import django.utils.timezone
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('synopsis', models.TextField(blank=True, verbose_name='описание')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('hide_uploader', models.BooleanField(default=False, verbose_name='анонимно')),
                ('approved', models.BooleanField(default=False, verbose_name='одобрен')),
                ('year', models.PositiveSmallIntegerField(default=materials.models.current_year, verbose_name='год')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='core.subject', verbose_name='предмет')),
                ('teachers', models.ManyToManyField(blank=True, related_name='materials', to='teachers.teacher', verbose_name='преподаватели')),
                ('terms', models.ManyToManyField(blank=True, related_name='materials', to='core.term', verbose_name='семестры')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_author', models.BooleanField(default=False, verbose_name='анонимно')),
                ('text', models.TextField(verbose_name='текст')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_comments', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('disliked_users', models.ManyToManyField(blank=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL)),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='materials.material', verbose_name='материал')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('author', 'material'), name='unique_comment_per_author_material')],
            },
        ),
    ]
