# Generated by Django 6.0.6 on 2026-06-24 22:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='отчество')),
                ('bio', models.TextField(blank=True, verbose_name='о преподавателе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos', verbose_name='фото')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='телефон')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='почта')),
                ('vk_page', models.CharField(blank=True, max_length=50, verbose_name='VK (без https://vk.com/)')),
                ('tg_page', models.CharField(blank=True, max_length=50, verbose_name='TG (без https://t.me/)')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='core.subject', verbose_name='предметы')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_author', models.BooleanField(default=False, verbose_name='анонимно')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('score_knowledge', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='знания')),
                ('score_skill', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='умение преподавать')),
                ('score_communication', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='общение')),
                ('score_freeloading', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='халявность')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reviews', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('disliked_users', models.ManyToManyField(blank=True, related_name='disliked_teacher_reviews', to=settings.AUTH_USER_MODEL)),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_teacher_reviews', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teachers.teacher', verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('surname', 'name', 'patronymic'), name='unique_teacher_fio'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'teacher'), name='unique_review_per_author_teacher'),
        ),
    ]
