# Generated by Django 6.0.6 on 2026-06-24 23:07

import attachments.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('materials', '0002_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('file', models.FileField(upload_to=attachments.models.file_upload_to, verbose_name='файл')),
                ('size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='размер (байт)')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='скачиваний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='library.book', verbose_name='книга')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='materials.material', verbose_name='материал')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='название')),
                ('image', models.ImageField(upload_to=attachments.models.image_upload_to, verbose_name='изображение')),
                ('size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='размер (байт)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='materials.material', verbose_name='материал')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ['order', 'id'],
            },
        ),
    ]
